### ISSUE TITLE
将 hook api 用于组件间通讯

### ISSUE THREAD

**Issue by fa93hws** [fa93hws/fa93hws.github.io#2]
使用 React 新发布的 Hook Api (https://reactjs.org/docs/hooks-intro.html) 以及 发布-订阅者模式 实现组件间通讯. 此方法可以替代传统架构中 Redux / Mobx 所担任的角色, 并显著缩小打包体积 . 得益于 Hook Api 的灵活性, 该方法不仅可以用于全局状态管理, 也可以实例化多个用于模块内状态管理(比如mobx), 甚至可以仅用于共享一个 state. 粒度完全自由.

**Comment by pengwangpengwang** [comment]
你好，请问有没有例子可以参考一下store那块的用法，不是很熟悉hooks

**Comment by pengwangpengwang** [comment]
你好，请问有没有例子可以参考一下store那块的用法，不是很熟悉hooks

**Comment by fa93hws** [comment]
> 你好，请问有没有例子可以参考一下store那块的用法，不是很熟悉hooks

https://github.com/fa93hws/fa93hws.github.io/blob/source/src/utils/shared-state.ts

**Comment by fa93hws** [comment]
哎，我居然连提交反馈都没做

**Comment by pengwangpengwang** [comment]
没有评论记录，提交万都不知道有没有，非常感谢分享




------------------ 原始邮件 ------------------
发件人: "Eric Wang"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午2:55
收件人: "fa93hws/fa93hws.github.io"<fa93hws.github.io@noreply.github.com>;
抄送: "王鹏"<1203923674@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [fa93hws/fa93hws.github.io] 将 hook api 用于组件间通讯 (#2)




哎，我居然连提交反馈都没做
